apiVersion: apps/v1
kind: Deployment
metadata:
  name: jekyll
  annotations:
  labels:
    app.kubernetes.io/component: jekyll
    app.kubernetes.io/instance: jekyll
    app.kubernetes.io/part-of: jekyll
    app.openshift.io/runtime: openshift
    app: jekyll
spec:
  progressDeadlineSeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: jekyll
  template:
    metadata:
      labels:
        app: jekyll
    spec:
      automountServiceAccountToken: false
      serviceAccountName: runasanyuid
      containers:
      - image: docker.io/jekyll/jekyll:latest
        command: ['jekyll', 'serve']
        #command: ['/usr/jekyll/bin/jekyll', 'serve']
        name: jekyll
        env:
          - name: JEKYLL_ROOTLESS
            value: '1'
        ports:
        - containerPort: 4000
          protocol: TCP
        resources: {}
        securityContext:
          #privileged: true
          allowPrivilegeEscalation: false
          #runAsNonRoot: true
          capabilities:
            drop: [ "ALL" ]
            #- CAP_NET_RAW
            #- CAP_AUDIT_WRITE
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /srv/jekyll
          name: jekyll-src-pvc
      enableServiceLinks: false
      restartPolicy: Always
      volumes:
      - name: jekyll-src-pvc
        persistentVolumeClaim:
          claimName: jekyll-src

      initContainers:
      - name: init-jekyll-src
        image: registry.access.redhat.com/ubi9/toolbox:latest
        command: ['sh', '-c',  'git clone $(GIT_REPO_URL) /src || { cd /src; git pull; }'  ]
        env:
          - name: GIT_REPO_URL
            valueFrom:
              configMapKeyRef:
                name: jekyll-configmap
                key: git-repo-url
        volumeMounts:
        - mountPath: /src
          name: jekyll-src-pvc
      volumes:
      - name: jekyll-src-pvc
        persistentVolumeClaim:
          claimName: jekyll-src
