apiVersion: v1
kind: Secret
metadata:
  name: satellite-provisioner-token
  namespace: satellite-vms
  annotations:
    kubernetes.io/service-account.name: satellite-provisioner
type: kubernetes.io/service-account-token
