# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.7

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-12-21T01:53:12Z"
  labels:
    app: jenkins-blueocean
  name: jenkins-blueocean
spec:
  containers:
  - image: docker.io/jenkinsci/blueocean:latest
    name: jenkins-blueocean
    ports:
    - containerPort: 8080
      hostPort: 18080
    - containerPort: 50000
      hostPort: 50000
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/jenkins_home
      name: jenkins-data-pvc
    - mountPath: /certs/client
      name: jenkins-docker-certs-pvc
      readOnly: true
  volumes:
  - name: jenkins-data-pvc
    persistentVolumeClaim:
      claimName: jenkins-data
  - name: jenkins-docker-certs-pvc
    persistentVolumeClaim:
      claimName: jenkins-docker-certs
      readOnly: true
